name: CI solamente

on: 
  push: 
    branches: [ master ] 
  workflow_dispatch: 

jobs: 
  build: 
    runs-on: ubuntu-latest 
    permissions: 
      contents: write 
      packages: write 
      id-token: write  # Agrega este permiso

    steps: 
      - name: Checkout repository 
        uses: actions/checkout@v4

      - name: Set up JDK 8 
        uses: actions/setup-java@v4  
        with: 
          java-version: '8' 
          distribution: 'adopt' 
          server-id: github  
          settings-path: ${{ github.workspace }}  

      - uses: gradle/actions/setup-gradle@v3 
        with: 
          gradle-version: 2.1  

      - name: Build del Front 
        working-directory: src/Clients 
        run: ./gradlew build  

      - name: Guardar artifact del Front en GitHub Actions
        uses: actions/upload-artifact@v4  
        with: 
          name: Clients 
          path: src/Clients/build/libs 

      - name: Build del Back 
        working-directory: src/Backend/OrderService 
        run: ./gradlew build test 

      - name: Dockerizar el Front y el Backend 
        run: |  
          cp src/Clients/build/libs/*.war deploy/docker/Clients/drop  
          docker build -t p2gps/web deploy/docker/Clients 
          cp src/Backend/OrderService/build/libs/ordering* deploy/docker/Order/drop  
          docker build -t p2gps/order deploy/docker/Order 

      - name: Login to DockerHub 
        uses: docker/login-action@v3  
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}  
          password: ${{ secrets.DOCKERHUB_PASSWORD }}  

      - name: Etiquetar con formato DockerHub 
        run: | 
          docker tag p2gps/web ${{ secrets.DOCKERHUB_USERNAME }}/p2gps:web 
          docker tag p2gps/order ${{ secrets.DOCKERHUB_USERNAME }}/p2gps:order 

      - name: Push a DockerHub 
        run: | 
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/p2gps:order 
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/p2gps:web

      - name: Log into Azure 
        uses: azure/login@v2 
        with: 
          client-id: ${{ secrets.AZURE_CLIENT_ID }} 
          tenant-id: ${{ secrets.AZURE_TENANT_ID }} 
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
          enable-AzPSSession: true 

      - name: Azure CLI script 
        uses: azure/CLI@v2 
        with: 
          azcliversion: latest 
          inlineScript: | 
            # Configura WEBSITES_ENABLE_APP_SERVICE_STORAGE
            az webapp config appsettings set --name p2gps --resource-group recursosGPS --settings WEBSITES_ENABLE_APP_SERVICE_STORAGE=TRUE
          
            # Inicia la aplicación web
            az webapp start --name p2gps --resource-group recursosGPS
